/*
 * T-Plan Robot, automated testing tool based on remote desktop technologies.
 * Copyright (C) 2009  T-Plan Limited (http://www.t-plan.co.uk),
 * Tolvaddon Energy Park, Cornwall, TR14 0HX, United Kingdom
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package com.tplan.robot.gui.plugin;

import com.tplan.robot.ApplicationSupport;
import java.awt.Font;
import java.util.ResourceBundle;
import javax.swing.UIManager;
import javax.swing.text.html.HTMLDocument;

/**
 * Panel with components displaying details of a particular plugin.
 * @product.signature
 */
class PluginDetailPanel extends javax.swing.JPanel {

    /** Creates new form PluginDetailPanel */
    public PluginDetailPanel() {
        initComponents();
        initLabels();

        // Set the JEditorPane default font to the JLabel one
        txpDesc.setContentType("text/html");
        Font font = UIManager.getFont("Label.font");
        String bodyRule = "body { font-family: " + font.getFamily() + "; " + "font-size: " + font.getSize() + "pt; }";
        ((HTMLDocument) txpDesc.getDocument()).getStyleSheet().addRule(bodyRule);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblName = new javax.swing.JLabel();
        btnInstall = new javax.swing.JButton();
        btnActivate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpDesc = new javax.swing.JEditorPane();
        btnConfig = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblName.setBackground(javax.swing.UIManager.getDefaults().getColor("MenuItem.selectionBackground"));
        lblName.setText(" ");
        lblName.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(lblName, gridBagConstraints);

        btnInstall.setText("Install");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(btnInstall, gridBagConstraints);

        btnActivate.setText("Activate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(btnActivate, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(360, 220));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(410, 205));
        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        txpDesc.setBorder(javax.swing.BorderFactory.createLoweredBevelBorder());
        txpDesc.setEditable(false);
        txpDesc.setMinimumSize(new java.awt.Dimension(350, 150));
        txpDesc.setOpaque(false);
        txpDesc.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane1.setViewportView(txpDesc);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        btnConfig.setText("Configure...");
        add(btnConfig, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivate;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnInstall;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JEditorPane txpDesc;
    // End of variables declaration//GEN-END:variables

    private void initLabels() {
        ResourceBundle res = ApplicationSupport.getResourceBundle();
        btnInstall.setText(res.getString("com.tplan.robot.pluginGui.btnInstall"));
        btnActivate.setText(res.getString("com.tplan.robot.pluginGui.btnEnable"));
        btnConfig.setText(res.getString("com.tplan.robot.pluginGui.btnConfigure"));
    }

    /**
     * @return the btnActivate
     */
    public javax.swing.JButton getBtnActivate() {
        return btnActivate;
    }

    /**
     * @return the btnInstall
     */
    public javax.swing.JButton getBtnInstall() {
        return btnInstall;
    }

    /**
     * @param btnInstall the btnInstall to set
     */
    public void setBtnInstall(javax.swing.JButton btnInstall) {
        this.btnInstall = btnInstall;
    }

    /**
     * @return the lblName
     */
    public javax.swing.JLabel getLblName() {
        return lblName;
    }

    /**
     * @return the txpDesc
     */
    public javax.swing.JEditorPane getTxpDesc() {
        return txpDesc;
    }

    public void clean() {
        txpDesc.setText("");
        lblName.setText(" ");
        btnActivate.setEnabled(false);
        btnInstall.setEnabled(false);
        btnConfig.setEnabled(false);
    }

    /**
     * @return the btnConfig
     */
    public javax.swing.JButton getBtnConfig() {
        return btnConfig;
    }
}
